# Generated by Django 5.0.4 on 2024-04-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Заказчик', 'Заказчик'), ('Исполнитель', 'Исполнитель')], default=None, max_length=30, null=True),
        ),
    ]
